<a href="https://colab.research.google.com/github/csoren66/Deep-Learning/blob/main/5_loss_or_cost_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

Implement Mean Absolute Error

In [6]:
def mae(y_true,y_predicted):
  total_error = 0
  for yt, yp in zip(y_true,y_predicted):
    total_error += abs(yt - yp)
  print("Total error:", total_error)

  mae = total_error / len(y_true)
  print("MAE:",mae)
  return mae

In [8]:
mae(y_predicted, y_true)

Total error: 2.5
MAE: 0.5


0.5

In [10]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [11]:
np.sum(np.abs(y_predicted - y_true))

2.5

Implement Log Loss or Binary Cross Entropy

In [12]:
np.log([0])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-inf])

In [13]:
epsilon = 1e-15

In [14]:
np.log([1e-15])

array([-34.53877639])

In [15]:
y_predicted

array([1, 1, 0, 0, 1])

In [19]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [20]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted]
y_predicted_new

[0.999999999999999, 0.999999999999999, 0, 0, 0.999999999999999]

In [21]:
y_predicted_new =np.array(y_predicted_new)

In [22]:
np.log(y_predicted_new)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-9.99200722e-16, -9.99200722e-16,            -inf,            -inf,
       -9.99200722e-16])

In [23]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in multiply
  """Entry point for launching an IPython kernel.


nan

In [24]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [25]:
log_loss(y_true, y_predicted)

17.2696280766844