<a href="https://colab.research.google.com/github/csoren66/Deep-Learning/blob/main/Word_embedding_using_keras_embedding_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [ ]:
reviews = ['nice food',
           'amazing restaurent',
           'too good',
           'just loved it!',
           'will go again',
           'horrible food',
           'never go there',
           'poor service',
           'poor quality',
           'needs improvements']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
one_hot("amazing restaurant", 30)

[27, 19]

In [ ]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[25, 10],
 [27, 3],
 [13, 20],
 [2, 21, 19],
 [20, 28, 17],
 [28, 10],
 [1, 28, 6],
 [3, 14],
 [3, 10],
 [13, 29]]

In [ ]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding = 'post')
padded_reviews

array([[25, 10,  0],
       [27,  3,  0],
       [13, 20,  0],
       [ 2, 21, 19],
       [20, 28, 17],
       [28, 10,  0],
       [ 1, 28,  6],
       [ 3, 14,  0],
       [ 3, 10,  0],
       [13, 29,  0]], dtype=int32)

In [ ]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, name = "embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [ ]:
X = padded_reviews
y = sentiment

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_2 (Flatten)         (None, 12)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(X, y, epochs=50, verbose =0)

In [ ]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 161ms/step - loss: 0.6240 - accuracy: 0.9000


0.8999999761581421

In [ ]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [ ]:
weights[25]

array([0.09557799, 0.02011721, 0.05031401, 0.01134655], dtype=float32)

In [ ]:
weights[10]

array([ 0.08604492, -0.04577602,  0.00550145,  0.00999895], dtype=float32)